### ISSUE TITLE
expo: command not found

### ISSUE THREAD

**Issue by tabahsetyoaji** [anoaland/anoa-cli#1]
**Environment:**
  ```
OS: macOS Mojave 10.14
  Node: 10.8.0
  Yarn: 1.9.4
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003
```

Description
hello, i have a problem when i run the command anoa init project_name , and i select Expo Boilerplate as shown in the attached screenshot
![whatsapp image 2018-11-07 at 3 39 56 pm](https://user-images.githubusercontent.com/37094134/48141191-ee177f80-e2dc-11e8-8d34-7ca4ab6afdef.jpeg)

**Comment by budiadiono** [comment]
Thank you @tabahsetyoaji, it should be fixed now.
