### ISSUE TITLE
Question: How to attach middleware to the store? 

### ISSUE THREAD

**Issue by esafirm** [anoaland/anoa-cli#11]
I'm kinda new to Typescript and the store creation is already using Anoa's `ReduxStore`. That makes me lost.

**Comment by budiadiono** [comment]
Go to `src/App.tsx` file -- under `prepare` function, you can attach middleware by passing it trough 2nd/3rd parameter of  `AppStore.init` function.

First parameter is to get the initial state, the second parameter for beforeMiddleware, and third parameter for afterMiddleware.

Example:

```
// src/App.tsx

async prepare(): Promise<void> {
    await AppStore.init(

      // promise function to returns initial redux state
      async () => {        
        return {
          // initial state as if any
        }        
      },

      // before middleware
      ({ dispatch, getState }) => next => action => {
        const { user } = getState().auth
        dispatch({ type: 'SOME_ACTION', payload: user })
        next(action)
      }

      // after middleware here...
    )
}
```

*before* or *after* here mean before and after redux-thunk middleware get invoked. To see how it works, you can take a look on  `ReduxStore.init` function on:  https://github.com/anoaland/anoa/blob/master/src/store/index.tsx#L41

**Comment by esafirm** [comment]
Thank you, this is really helpful. Didn't notice the `prepare` function before. 
Closing the issue 😄

**Comment by budiadiono** [comment]
My bad to not document it 😅 By the way, thank you for this question -- this give me some thoughts to create an overload parameter for `AppStore.init` that now we can initialize it this way:

```
await AppStore.init({
  // redux initial state (optional)
  initialState: {
    todo: {
      foo: 'foo'
    }
  },
  // redux middleware before redux thunk middleware attached (optional)
  beforeMiddleware: awesomeMiddleware,

  // redux middleware before redux thunk middleware attached (optional)
  afterMiddleware: logOrSomethingMiddleware
})
```

Instead of using ordered parameter. Also for multiple middlewares we can set it in array like so:

```
await AppStore.init({
  beforeMiddleware: [
    awesomeMiddleware,
    anotherMiddleware    
  ],
  afterMiddleware: [
    logOrSomethingMiddleware,
    anotherLogMiddleware,
  ]
})
```

I've just publish this changes in anoa version 0.0.4.
